freebsd_instance:
  image: freebsd-11-2-release-amd64

task:
  install_script:
    - sudo pkg install -y p5-Dist-Zilla p5-App-cpanminus
    - sudo dzil authordeps --missing | cpanm -n
    - sudo dzil listdeps --missing | cpanm -n
  script:
    - dzil test -v
  
